import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "案例",
      icon: "laptop-code",
      prefix: "demo/",
      link: "demo/",
      children: "structure",
    },
    {
      text: "文档",
      icon: "book",
      prefix: "guide/",
      children: "structure",
    },
    "slides",
  ],
  "/book/": [
    "README.md",
    "MYWORD.md",
    "00-On-Java-8.md",
    "00-Preface.md",
    "00-Introduction.md",
    "01-What-is-an-Object.md",
    "02-Installing-Java-and-the-Book-Examples.md",
    "03-Objects-Everywhere.md",
    "04-Operators.md",
    "05-Control-Flow.md",
    "06-Housekeeping.md",
    "07-Implementation-Hiding.md",
    "08-Reuse.md",
    "09-Polymorphism.md",
    "10-Interfaces.md",
    "11-Inner-Classes.md",
    "12-Collections.md",
    "13-Functional-Programming.md",
    "14-Streams.md",
    "15-Exceptions.md",
    "16-Validating-Your-Code.md",
    "17-Files.md",
    "18-Strings.md",
    "19-Type-Information.md",
    "20-Generics.md",
    "21-Arrays.md",
    "22-Enumerations.md",
    "23-Annotations.md",
    "24-Concurrent-Programming.md",
    "25-Patterns.md",
    "Appendix-Becoming-a-Programmer.md",
    "Appendix-Benefits-and-Costs-of-Static-Type-Checking.md",
    "Appendix-Collection-Topics.md",
    "Appendix-Data-Compression.md",
    "Appendix-IO-Streams.md",
    "Appendix-Javadoc.md",
    "Appendix-Low-Level-Concurrency.md",
    "Appendix-New-IO.md",
    "Appendix-Object-Serialization.md",
    "Appendix-Passing-and-Returning-Objects.md",
    "Appendix-Programming-Guidelines.md",
    "Appendix-Standard-IO.md",
    "Appendix-Supplements.md",
    "Appendix-The-Positive-Legacy-of-C-plus-plus-and-Java.md",
    "Appendix-Understanding-equals-and-hashCode.md",
    "GLOSSARY.md",
  ],
});
